
export type VideoMode = 't2v' | 'i2v';

// Defines the types for the main application features/models.
export type AppFeature =
  'prompt-gen' | // Represents the new Prompt Generator
  'seedance-1.5pro' |
  'wan-2.6' |
  'kling-2.6' |
  'grok-imagine' |
  'hailuo-2.3' |
  'sora-2' |
  'veo-3.1'; // The new demo Veo 3.1 model, distinct from the 'video-gen' functionality for now.

// Expanded type definition for VideoGenerationOperation to match the actual API response
// and facilitate polling.
export interface VideoGenerationOperation {
  name: string;
  metadata?: {
    '@type': string;
    createTime: string;
    done: boolean;
    operation: string;
    progress: number;
  };
  done: boolean;
  response?: {
    '@type': string;
    generatedVideos?: Array<{
      video: {
        uri: string;
        aspectRatio: string;
        resolution: string;
      };
    }>;
  };
  error?: {
    code: number;
    message: string;
  };
}

// Interface for the structured video prompt generated by the LLM
export interface DetailedVideoPrompt {
  title: string;
  genre?: string;
  characters?: Array<{
    name: string;
    description: string;
    costume?: string;
  }>;
  scenario: string;
  background: string;
  camera_angle?: string; // New field for camera angle
  style?: string; // New field for video style/filter
  dialogue_snippets?: string[];
  music_mood?: string;
  sound_effects?: string[];
  full_text_prompt: string;
}

// Interface for local representation of a video file for UI display and upload
export interface VideoFile {
  id: string;
  file: File;
  preview: string; // Data URL for local preview
}

// Sub-modes for Grok Imagine
export type GrokImagineMode = 'i2v' | 't2v'; // 'upscale' removed
